/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "stm32f411xx.h"

#include "simplertos.h"
#include "scheduler_settings.h"


uint32_t stack_blinky1[40];
OSThread blinky1;
void main_blinky1()
{
	while(1)
	{
		GPIO_WriteToOutputPin(GPIOD, LED_ORANGE, ENABLE);
		simple_delay(TICKS_PER_SEC/2U);

		GPIO_WriteToOutputPin(GPIOD, LED_ORANGE, DISABLE);
		simple_delay(TICKS_PER_SEC/2U);
	}
}

uint32_t stack_blinky2[40];
OSThread blinky2;
void main_blinky2()
{
	while(1)
	{
		GPIO_WriteToOutputPin(GPIOD, LED_RED, ENABLE);
		simple_delay(TICKS_PER_SEC/3U);

		GPIO_WriteToOutputPin(GPIOD, LED_RED, DISABLE);
		simple_delay(TICKS_PER_SEC/4U);
	}
}

uint32_t stack_blinky3[40];
OSThread blinky3;
void main_blinky3()
{
	while(1)
	{
		GPIO_WriteToOutputPin(GPIOD, LED_BLUE, ENABLE);
		simple_delay(TICKS_PER_SEC/2U);

		GPIO_WriteToOutputPin(GPIOD, LED_BLUE, DISABLE);
		simple_delay(TICKS_PER_SEC/3U);
	}
}


uint32_t stack_blinky4[40];
OSThread blinky4;
void main_blinky4()
{
	while(1)
	{
		GPIO_WriteToOutputPin(GPIOD, LED_GREEN, ENABLE);
		simple_delay(TICKS_PER_SEC/3U);

		GPIO_WriteToOutputPin(GPIOD, LED_GREEN, DISABLE);
		simple_delay(TICKS_PER_SEC/3U);
	}
}


uint32_t stack_idleThread[40];
__attribute__((noreturn)) int main(void)
{
	Periph_Init();
	OS_init(stack_idleThread, sizeof(stack_idleThread));


	OS_thread_create(&blinky1,
			&main_blinky1,
			stack_blinky1, sizeof(stack_blinky1));

	OS_thread_create(&blinky2,
			&main_blinky2,
			stack_blinky2, sizeof(stack_blinky2));

	OS_thread_create(&blinky3,
			&main_blinky3,
			stack_blinky3, sizeof(stack_blinky3));

	OS_thread_create(&blinky4,
			&main_blinky4,
			stack_blinky4, sizeof(stack_blinky4));

	OS_run();
}



